### PR TITLE
Change transportation units to MWh

### PR DESCRIPTION
**Pull request by daniel-thom**

### CODE REVIEW

**Comment by ahcyip** [comment]
were the values in the data divided by 1000?

**Comment by daniel-thom** [comment]
> were the values in the data divided by 1000?

The value of kWh in this file caused dsgrid to leave the transportation values in kWh rather than convert them to MWh, which is what happens for all other end uses.

**Comment by ahcyip** [comment]
thanks that makes perfect sense
so, kWh in datasets/dimensions/enduses.csv and MWh in projects/dimensions/enduses.csv

**Comment by daniel-thom** [comment]
> thanks that makes perfect sense
> so, kWh in datasets/dimensions/enduses.csv and MWh in projects/dimensions/enduses.csv

More specifically, the dataset can put its preferred units. All project end uses should use the same unit.

**Review by elainethale — APPROVED** [review]

**Pull request merged**
